In [ ]:
Ppl=['b','b','g','b','g']
Ppl.sort()
print(Ppl)

['b', 'b', 'b', 'g', 'g']

In [ ]:
#Types of Ai
#gen ai = works for human equality , does not exist
#narrow ai = works for specific task, ex= google translator
#trong ai = works for all tasks

In [ ]:
#Computer vision
#Branch of AI that enables computers to see, analyze, understand images, videos

In [ ]:
import numpy as np
x = np.array([10,20,30])
y = x + 10
print(y)

[20 30 40]

In [ ]:

print(np.sum(x))

60

In [ ]:
print(np.mean(x))

20.0

In [ ]:
print(np.max(x))

30

In [ ]:
print(np.min(x))

10

In [ ]:
import pandas as pd
data={
    'name': ['mohan','rohan','verma','ananya'],
    'marks': [98,78,79,88]
}
print(data)
df=pd.DataFrame(data)
print (df)

{'name': ['mohan', 'rohan', 'verma', 'ananya'], 'marks': [98, 78, 79, 88]}
     name  marks
0   mohan     98
1   rohan     78
2   verma     79
3  ananya     88

In [ ]:
df.head()

     name  marks
0   mohan     98
1   rohan     78
2   verma     79
3  ananya     88

In [ ]:
df.name

0     mohan
1     rohan
2     verma
3    ananya
Name: name, dtype: object

In [ ]:
print(df['marks'].mean())

85.75

In [ ]:
print(df['marks'].max())

98

In [ ]:
print(df['marks'].min())

78

In [ ]:
print(df[df['marks']>70]['name'])

0     mohan
1     rohan
2     verma
3    ananya
Name: name, dtype: object

In [ ]:
### assignment 1

In [ ]:
def calculate_hra(basic):
    return 0.2*basic
def calculate_da(basic):
    return 0.1*basic
def calculate_net_salary(basic):
    hra = calculate_hra(basic)
    da = calculate_da(basic)
    net_salary = basic + hra + da
    print("net salary:", net_salary)

def main():
    n=str(input("Enter the employee name:"))
    basic = float(input("Enter the basic salary:"))
    calculate_net_salary(basic)

if __name__=="__main__":
    main()

Enter the employee name:Gurmannat
Enter the basic salary:1000000
net salary: 1300000.0

In [ ]:
def calculate_total(marks):
    t=sum(marks)
    return t
def calculate_percentage(total, num_subjects):
    p=(total/num_subjects)
    return p
def assign_grade(percentage):
    if percentage >=90:
       return "A"
    elif percentage>=75 and percentage<90:
       return "B"
    elif percentage>= 60 and percentage<75:
       return "C"
    elif percentage>=40 and percentage<60:
       return "D"
    else:
       return "F"
def main():
    marks=[float(input("Enter marks for subject{}".format(i+1))) for i in range(5)]
    total=calculate_total(marks)
    percentage=calculate_percentage(total,5)
    grade=assign_grade(percentage)
    print("Total marks:{}". format(total))
    print("Percentage: {}".format(percentage))
    print("Grade: {}".format(grade))
if __name__=="__main__":
    main()

Enter marks for subject198
Enter marks for subject277
Enter marks for subject395
Enter marks for subject492
Enter marks for subject583
Total marks:445.0
Percentage: 89.0
Grade: B

In [ ]:
def

Assignment 2

In [ ]:
# file handling question

In [ ]:
file = open("marks.txt","w+")
file.write("Varun : 25 \nKumar : 67 \nAnjali : 44 \nGurmannat : 93 \nVerma : 88")
file.close()

file = open("marks.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : 25
Kumar : 67
Anjali : 44
Gurmannat : 93
Verma : 88

In [ ]:
file = open("marks.txt", "r")

pass_count = 0
fail_count = 0

for i in file:
  name, marks = i.split(":")
  marks = int(marks.strip())
  name = name.strip()

  if marks > 45:
    print(name, " has passed the exam with", marks,"marks")
    pass_count +=1
  else:
    print(name,"has failed the exam with", marks,"marks")
    fail_count +=1
file.close()

print("\nPass students:", pass_count)
print("fail students", fail_count)

Varun has failed the exam with 25 marks
Kumar  has passed the exam with 67 marks
Anjali has failed the exam with 44 marks
Gurmannat  has passed the exam with 93 marks
Verma  has passed the exam with 88 marks

Pass students: 3
fail students 2

In [ ]:
file = open("salary.txt","w+")
file.write("Varun : 47000 \nAnjali : 44000 \nGurmannat : 93000 \nVerma : 67000")
file.close()

file = open("salary.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : 47000
Anjali : 44000
Gurmannat : 93000
Verma : 67000

In [ ]:
file = open("salary.txt", "r")

greater_count = 0

for i in file:
  name, salary = i.split(":")
  salary = int(salary.strip())
  name = name.strip()

  if salary > 50000:
    print(name, " has a salary of", salary)
    greater_count +=1

file.close()

print("\nNo. of employees with salary >=50000:", greater_count)

Gurmannat  has a salary of 93000
Verma  has a salary of 67000

No. of employees with salary >=50000: 2

In [ ]:
file = open("attendance.txt","w+")
file.write("Varun : Absent \nAnjali : Present \nGurmannat : Present \nVerma : Absent")
file.close()

file = open("attendance.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : Absent
Anjali : Present
Gurmannat : Present
Verma : Absent

In [ ]:
file = open("attendance.txt", "r")

present_employees = 0
absent_employees = 0

for i in file:
  name, attendance_status = i.split(":")
  name = name.strip(

  )
  attendance_status = attendance_status.strip()

  if attendance_status == "Absent":
    print(name, ": Absent")
    absent_employees += 1
  else:
    present_employees += 1

file.close()

print("\nNo. of present employees:", present_employees)
print("No. of absent employees:", absent_employees)

Varun : Absent
Verma : Absent

No. of present employees: 2
No. of absent employees: 2