In [ ]:
### assignment 1

In [ ]:
def calculate_hra(basic):
    return 0.2*basic
def calculate_da(basic):
    return 0.1*basic
def calculate_net_salary(basic):
    hra = calculate_hra(basic)
    da = calculate_da(basic)
    net_salary = basic + hra + da
    print("net salary:", net_salary)

def main():
    n=str(input("Enter the employee name:"))
    basic = float(input("Enter the basic salary:"))
    calculate_net_salary(basic)

if __name__=="__main__":
    main()

Enter the employee name:Gurmannat
Enter the basic salary:1000000
net salary: 1300000.0

In [ ]:
def calculate_total(marks):
    t=sum(marks)
    return t
def calculate_percentage(total, num_subjects):
    p=(total/num_subjects)
    return p
def assign_grade(percentage):
    if percentage >=90:
       return "A"
    elif percentage>=75 and percentage<90:
       return "B"
    elif percentage>= 60 and percentage<75:
       return "C"
    elif percentage>=40 and percentage<60:
       return "D"
    else:
       return "F"
def main():
    marks=[float(input("Enter marks for subject{}".format(i+1))) for i in range(5)]
    total=calculate_total(marks)
    percentage=calculate_percentage(total,5)
    grade=assign_grade(percentage)
    print("Total marks:{}". format(total))
    print("Percentage: {}".format(percentage))
    print("Grade: {}".format(grade))
if __name__=="__main__":
    main()

Enter marks for subject199
Enter marks for subject287
Enter marks for subject398
Enter marks for subject487
Enter marks for subject590
Total marks:461.0
Percentage: 92.2
Grade: A

In [ ]:
def grade(p):
    if p >= 90:
        return "A"
    elif p >= 75:
        return "B"
    elif p >= 60:
        return "C"
    elif p >= 40:
        return "D"
    return "F"

students = {}
n = int(input("Enter number of students: "))

for i in range(n):
    roll = input("Roll No: ")
    name = input("Name: ")

    marks = []
    for j in range(5):
        marks.append(int(input(f"Subject {j+1}: ")))

    total = sum(marks)
    per = total / 5

    students[roll] = {
        "name": name,
        "marks": marks,
        "percentage": per,
        "grade": grade(per)
    }

print("\nStudent Records")
for roll, data in students.items():
    print(roll, data["name"], data["percentage"], "%", data["grade"])

topper = max(students, key=lambda x: students[x]["percentage"])

print("\nTopper:")
print(students[topper]["name"], "-", students[topper]["percentage"], "%")

Enter number of students: 2
Roll No: 1
Name: Gurmannat
Subject 1: 99
Subject 2: 96
Subject 3: 95
Subject 4: 94
Subject 5: 98
Roll No: 2
Name: Mohan
Subject 1: 90
Subject 2: 97
Subject 3: 87
Subject 4: 88
Subject 5: 86

Student Records
1 Gurmannat 96.4 % A
2 Mohan 89.6 % B

Topper:
Gurmannat - 96.4 %

Assignment 2

In [ ]:
# file handling question

In [ ]:
file = open("marks.txt","w+")
file.write("Varun : 25 \nKumar : 67 \nAnjali : 44 \nGurmannat : 93 \nVerma : 88")
file.close()

file = open("marks.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : 25
Kumar : 67
Anjali : 44
Gurmannat : 93
Verma : 88

In [ ]:
file = open("marks.txt", "r")

pass_count = 0
fail_count = 0

for i in file:
  name, marks = i.split(":")
  marks = int(marks.strip())
  name = name.strip()

  if marks > 45:
    print(name, " has passed the exam with", marks,"marks")
    pass_count +=1
  else:
    print(name,"has failed the exam with", marks,"marks")
    fail_count +=1
file.close()

print("\nPass students:", pass_count)
print("fail students", fail_count)

Varun has failed the exam with 25 marks
Kumar  has passed the exam with 67 marks
Anjali has failed the exam with 44 marks
Gurmannat  has passed the exam with 93 marks
Verma  has passed the exam with 88 marks

Pass students: 3
fail students 2

In [ ]:
file = open("salary.txt","w+")
file.write("Varun : 47000 \nAnjali : 44000 \nGurmannat : 93000 \nVerma : 67000")
file.close()

file = open("salary.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : 47000
Anjali : 44000
Gurmannat : 93000
Verma : 67000

In [ ]:
file = open("salary.txt", "r")

greater_count = 0

for i in file:
  name, salary = i.split(":")
  salary = int(salary.strip())
  name = name.strip()

  if salary > 50000:
    print(name, " has a salary of", salary)
    greater_count +=1

file.close()

print("\nNo. of employees with salary >=50000:", greater_count)

Gurmannat  has a salary of 93000
Verma  has a salary of 67000

No. of employees with salary >=50000: 2

In [ ]:
file = open("attendance.txt","w+")
file.write("Varun : Absent \nAnjali : Present \nGurmannat : Present \nVerma : Absent")
file.close()

file = open("attendance.txt","r")
cont = file.read()
print(cont)
file.close()

Varun : Absent
Anjali : Present
Gurmannat : Present
Verma : Absent

In [ ]:
file = open("attendance.txt", "r")

present_employees = 0
absent_employees = 0

for i in file:
  name, attendance_status = i.split(":")
  name = name.strip(

  )
  attendance_status = attendance_status.strip()

  if attendance_status == "Absent":
    print(name, ": Absent")
    absent_employees += 1
  else:
    present_employees += 1

file.close()

print("\nNo. of present employees:", present_employees)
print("No. of absent employees:", absent_employees)

Varun : Absent
Verma : Absent

No. of present employees: 2
No. of absent employees: 2

Assignment 3

In [ ]:
##numpy,pandas question

In [ ]:
import pandas as pd
import numpy as np
#Read csv file
df = pd.read_csv("/content/drive/MyDrive/product.csv")
df.columns = df.columns.str.strip() # Clean column names
df

       Product  Price
0       Laptop  50000
1      Mobile   20000
2      Tablet   30000
3  Headphones    7000
4  Smartwatch   10000

In [ ]:
# calculate average price using Numpy
avg_price = np.mean(df["Price"])
print("Average price:", avg_price)

Average price: 23400.0

In [ ]:
# function to display products above average price
def above_average_products(data, avg):
    print("\nProducts priced above average:")
    for index, row in data.iterrows():
        if row["Price"] > avg:
            print(row["Product"],"-", row["Price"])
above_average_products(df, avg_price)

Products priced above average:
Laptop - 50000
Tablet  - 30000

In [ ]:
import pandas as pd
import numpy as np
#Read csv file
df = pd.read_csv("/content/drive/MyDrive/Day, Temperature.csv")
df.columns = df.columns.str.strip() # Clean column names
df

         Day  Temperature
0     Sunday           18
1     Monday           25
2   Tuesday            32
3  Wednesday           20
4   Thursday           35
5     Friday           27
6   Saturday           19

In [ ]:
#using numpy to calculate highest,lowest and average temperature
highest_temp = np.max(df["Temperature"])
lowest_temp = np.min(df["Temperature"])
avg_temp = np.mean(df["Temperature"])

print("Highest temperature:", highest_temp)
print("Lowest temperature:", lowest_temp)
print("Average temperature:", avg_temp)

Highest temperature: 35
Lowest temperature: 18
Average temperature: 25.142857142857142

In [ ]:
#function to classify temperature
def classify_temp(temp):
    if temp < 20:
       return "Cold"
    elif temp <= 30:
         return "Moderate"
    else:
         return "Hot"
for temp in df["Temperature"]:
  print(temp, classify_temp(temp))

18 Cold
25 Moderate
32 Hot
20 Moderate
35 Hot
27 Moderate
19 Cold

In [ ]:
# Display category for each day
print("\nCategory for each day:")
for index, row in df.iterrows():
    print(row["Day"], "-", classify_temp(row["Temperature"]))

Category for each day:
Sunday - Cold
Monday - Moderate
Tuesday  - Hot
Wednesday - Moderate
Thursday - Hot
Friday - Moderate
Saturday - Cold